tags:
  - name: Risks
consumes:
  - application/json
summary: Delete risks by id
description: Endpoint to delete risk register, base on one id risk.
parameters:
  - in: header
    name: Authorization
    value: Bearer
    required: true
  - name: risk_id
    in: path
    type: integer
    required: true
    description: The ID of the risk to delete.
responses:
  200:
    description: Risks deleted successfully
  401:
    description: Fails to get items due to authentication error
  500:
    description: Server error