tags:
  - name: Risks history
consumes:
  - application/json
summary: Get all risks history
description: Endpoint to get all risk history register in the database.
parameters:
  - in: header
    name: Authorization
    value: Bearer
    required: true
  - name: page
    in: path
    type: integer
    required: true
    value: 1
    description: Number of page.
responses:
  200:
    description: Risks history
  401:
    description: Fails to get items due to authentication error