tags:
  - name: Risks history
consumes:
  - application/json
summary: Get all risks history
description: Endpoint to get all risk history register in the database.
parameters:
  - in: header
    name: Authorization
    value: Bearer
    required: true
responses:
  200:
    description: Risks history
  401:
    description: Fails to get items due to authentication error