tags:
  - name: Risks history
consumes:
  - application/json
summary: Create new risk
description: Endpoint to create new risk history register in the database.
parameters:
  - in: header
    name: Authorization
    value: Bearer
    type: string
    required: false
  - in: body
    name: risk_history
    description: Risk history object
    required: true
    schema:
      type: object
      properties:
        title:
          type: string
          description: The new value for the title field.
        impact:
          type: string
          description: The new value for the impact field.
        probability:
          type: number
          format: float
          description: The new value for the probability field.
        description:
          type: string
          description: The new value for the description field.
        risk_id:
          type: integer
          description: The new value for the risk_id field.
        user_id:
          type: integer
          description: The new value for the user_id field.
responses:
  201:
    description: Risk history has been added successfully
  401:
    description: Fails to get items due to authentication error
  500:
    description: Server error
