"""empty message

Revision ID: 71c169d644b7
Revises: 06e12a893c98
Create Date: 2023-06-29 20:02:19.464764

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "71c169d644b7"
down_revision = "06e12a893c98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risks_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risks_history", schema=None) as batch_op:
        batch_op.drop_column("title")

    # ### end Alembic commands ###
